WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
using world size: 8 and model-parallel size: 8 
> padded vocab (size: 150528) with 0 dummy tokens (new size: 150528)
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
> initializing model parallel with size 8
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 46, in main
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 46, in main
    config = BaseConfig.from_yaml_file(task_config_path)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 147, in from_yaml_file
    config = BaseConfig.from_yaml_file(task_config_path)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 147, in from_yaml_file
    return cls.from_yaml(in_file, decoder=decoder,
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 134, in from_yaml
    return cls.from_yaml(in_file, decoder=decoder,
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 134, in from_yaml
    o = decoder(string_or_stream, **decoder_kwargs)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    o = decoder(string_or_stream, **decoder_kwargs)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
      File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
return load(stream, SafeLoader)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
> Loading task configs
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
    return loader.get_single_data()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    return loader.get_single_data()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 46, in main
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 46, in main
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 46, in main
    config = BaseConfig.from_yaml_file(task_config_path)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 147, in from_yaml_file
    config = BaseConfig.from_yaml_file(task_config_path)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 147, in from_yaml_file
    node = self.get_single_node()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    node = self.get_single_node()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
    return cls.from_yaml(in_file, decoder=decoder,
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 134, in from_yaml
    config = BaseConfig.from_yaml_file(task_config_path)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 147, in from_yaml_file
    return cls.from_yaml(in_file, decoder=decoder,
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 134, in from_yaml
    document = self.compose_document()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
    document = self.compose_document()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
    o = decoder(string_or_stream, **decoder_kwargs)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    o = decoder(string_or_stream, **decoder_kwargs)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    return cls.from_yaml(in_file, decoder=decoder,
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 134, in from_yaml
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 46, in main
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 46, in main
        return load(stream, SafeLoader)node = self.compose_node(None, None)

  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_node(None, None)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    return load(stream, SafeLoader)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    o = decoder(string_or_stream, **decoder_kwargs)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    config = BaseConfig.from_yaml_file(task_config_path)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 147, in from_yaml_file
    config = BaseConfig.from_yaml_file(task_config_path)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 147, in from_yaml_file
    node = self.compose_mapping_node(anchor)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    return loader.get_single_data()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.compose_mapping_node(anchor)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    return loader.get_single_data()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    return load(stream, SafeLoader)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return cls.from_yaml(in_file, decoder=decoder,
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 134, in from_yaml
    return cls.from_yaml(in_file, decoder=decoder,
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 134, in from_yaml
    node = self.get_single_node()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    node = self.get_single_node()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    while not self.check_event(MappingEndEvent):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    while not self.check_event(MappingEndEvent):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    return loader.get_single_data()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    o = decoder(string_or_stream, **decoder_kwargs)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    o = decoder(string_or_stream, **decoder_kwargs)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    document = self.compose_document()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
    document = self.compose_document()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.get_single_node()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    return load(stream, SafeLoader)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return load(stream, SafeLoader)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    self.current_event = self.state()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    self.current_event = self.state()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    node = self.compose_node(None, None)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    document = self.compose_document()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
    return loader.get_single_data()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    return loader.get_single_data()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.compose_mapping_node(anchor)
    node = self.compose_node(None, None)  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 127, in compose_mapping_node

  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 46, in main
    if self.check_token(KeyToken):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 115, in check_token
    if self.check_token(KeyToken):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 115, in check_token
    node = self.get_single_node()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    node = self.get_single_node()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    while not self.check_event(MappingEndEvent):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    config = BaseConfig.from_yaml_file(task_config_path)
    node = self.compose_mapping_node(anchor)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 147, in from_yaml_file

  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    document = self.compose_document()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
    document = self.compose_document()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
    while not self.check_event(MappingEndEvent):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    while self.need_more_tokens():
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    while self.need_more_tokens():
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    self.current_event = self.state()
      File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    self.current_event = self.state()node = self.compose_node(None, None)

  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_node(None, None)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    return cls.from_yaml(in_file, decoder=decoder,
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.py", line 134, in from_yaml
    self.current_event = self.state()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 115, in check_token
    if self.check_token(KeyToken):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 115, in check_token
    self.stale_possible_simple_keys()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    self.stale_possible_simple_keys()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    node = self.compose_mapping_node(anchor)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    node = self.compose_mapping_node(anchor)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    if self.check_token(KeyToken):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 115, in check_token
    o = decoder(string_or_stream, **decoder_kwargs)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    while not self.check_event(MappingEndEvent):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    while self.need_more_tokens():
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    while self.need_more_tokens():
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    while self.need_more_tokens():
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    while not self.check_event(MappingEndEvent):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    return load(stream, SafeLoader)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    raise ScannerError("while scanning a simple key", key.mark,
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerErroryaml.scanner.ScannerError: while scanning a simple key
  in "tasks/ethnic/CROWS_test.yaml", line 4, column 1
could not find expected ':'
  in "tasks/ethnic/CROWS_test.yaml", line 5, column 1
: while scanning a simple key
  in "tasks/ethnic/CROWS_test.yaml", line 4, column 1
could not find expected ':'
  in "tasks/ethnic/CROWS_test.yaml", line 5, column 1
    self.stale_possible_simple_keys()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    self.stale_possible_simple_keys()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    self.stale_possible_simple_keys()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    self.current_event = self.state()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    self.current_event = self.state()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    return loader.get_single_data()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    raise ScannerError("while scanning a simple key", key.mark,
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerErroryaml.scanner.ScannerError    raise ScannerError("while scanning a simple key", key.mark,
: while scanning a simple key
  in "tasks/ethnic/CROWS_test.yaml", line 4, column 1
could not find expected ':'
  in "tasks/ethnic/CROWS_test.yaml", line 5, column 1
yaml.scanner: .while scanning a simple key
  in "tasks/ethnic/CROWS_test.yaml", line 4, column 1
could not find expected ':'
  in "tasks/ethnic/CROWS_test.yaml", line 5, column 1ScannerError
: while scanning a simple key
  in "tasks/ethnic/CROWS_test.yaml", line 4, column 1
could not find expected ':'
  in "tasks/ethnic/CROWS_test.yaml", line 5, column 1
    node = self.get_single_node()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    if self.check_token(KeyToken):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 115, in check_token
    if self.check_token(KeyToken):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 115, in check_token
    document = self.compose_document()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
    while self.need_more_tokens():
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    while self.need_more_tokens():
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    node = self.compose_node(None, None)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    self.stale_possible_simple_keys()    
node = self.compose_mapping_node(anchor)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/composer.py", line 127, in compose_mapping_node
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "tasks/ethnic/CROWS_test.yaml", line 4, column 1
could not find expected ':'
  in "tasks/ethnic/CROWS_test.yaml", line 5, column 1
    while not self.check_event(MappingEndEvent):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "tasks/ethnic/CROWS_test.yaml", line 4, column 1
could not find expected ':'
  in "tasks/ethnic/CROWS_test.yaml", line 5, column 1
    self.current_event = self.state()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "tasks/ethnic/CROWS_test.yaml", line 4, column 1
could not find expected ':'
  in "tasks/ethnic/CROWS_test.yaml", line 5, column 1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 650513) of binary: /mnt/yrfs/qinkai/miniconda3/envs/largescale/bin/python
Traceback (most recent call last):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.0', 'console_scripts', 'torchrun')())
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/yrfs/xuyifan/GLM-130B/evaluate.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-09-25_16:13:06
  host      : node14
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 650514)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-09-25_16:13:06
  host      : node14
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 650516)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2022-09-25_16:13:06
  host      : node14
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 650518)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2022-09-25_16:13:06
  host      : node14
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 650519)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2022-09-25_16:13:06
  host      : node14
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 650522)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2022-09-25_16:13:06
  host      : node14
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 650523)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2022-09-25_16:13:06
  host      : node14
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 650524)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-09-25_16:13:06
  host      : node14
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 650513)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
