WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
using world size: 8 and model-parallel size: 8 
> padded vocab (size: 150528) with 0 dummy tokens (new size: 150528)
> initializing model parallel with size 8
> Loading task configs
    Task ETHOS_oneshot loaded from config tasks/ethnic/ETHOS_oneshot.yaml
    Task ETHOS_zeroshot loaded from config tasks/ethnic/ETHOS_zeroshot.yaml
> Successfully load 2 tasks
> Set tokenizer as a icetk-glm-130B tokenizer! Now you can get_tokenizer() everywhere.
global rank 7 is loading checkpoint /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_07_model_states.pt
global rank 2 is loading checkpoint /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_02_model_states.pt
global rank 3 is loading checkpoint /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_03_model_states.pt
global rank 6 is loading checkpoint /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_06_model_states.pt
global rank 5 is loading checkpoint /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_05_model_states.pt
global rank 1 is loading checkpoint /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_01_model_states.pt
global rank 4 is loading checkpoint /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_04_model_states.pt
global rank 0 is loading checkpoint /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_00_model_states.pt
  successfully loaded /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_03_model_states.pt
  successfully loaded /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_07_model_states.pt
  successfully loaded /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_06_model_states.pt
  successfully loaded /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_02_model_states.pt
  successfully loaded /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_04_model_states.pt
  successfully loaded /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_00_model_states.pt
  successfully loaded /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_01_model_states.pt
  successfully loaded /mnt/yrfs/aohan/checkpoints/glm-130b-sat/49300/mp_rank_05_model_states.pt
> Checkpoint loaded in 24.0s


MultiChoiceTaskConfig(name='ETHOS_oneshot', type=<TaskType.MULTICHOICE: 'mul'>, path='data/ETHOS/oneshot', module=None, metrics=['F1_mul'], use_task_mask=False, use_multitask_encoding=False, unidirectional=False, max_seq_length=2048, file_pattern={'test': '**/oneshot.jsonl'}, micro_batch_size=32)
Evaluating task ETHOS_oneshot:
    Evaluating group test:
Evaluation results of task ETHOS_oneshot:
      Group test: 
Finish task ETHOS_oneshot in 0.0s.


GenerationTaskConfig(name='ETHOS_zeroshot', type=<TaskType.GENERATION: 'gen'>, path='data/ETHOS/zeroshot', module=None, metrics=['EM', 'F1'], use_task_mask=False, use_multitask_encoding=False, unidirectional=False, max_seq_length=2048, file_pattern={'test': '**/zeroshot.jsonl'}, micro_batch_size=1, sampling_strategy='BaseStrategy', num_beams=4, length_penalty=1.0, no_repeat_ngram_size=3, min_gen_length=0, max_gen_length=128)
Evaluating task ETHOS_zeroshot:
    Evaluating group test:
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 62, in main
    evaluate_all_tasks(args.data_path, model, tokenizer, args.task, task_classes)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 36, in evaluate_all_tasks
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 62, in main
    task.evaluate()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 74, in evaluate
    evaluate_all_tasks(args.data_path, model, tokenizer, args.task, task_classes)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 36, in evaluate_all_tasks
    task.evaluate()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 74, in evaluate
    dataset = self.build_dataset(file)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 167, in build_dataset
    dataset = self.build_dataset(file)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 167, in build_dataset
    return GenerationTaskDataset(join(self.config.path, relative_path), self.config)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 54, in __init__
    return GenerationTaskDataset(join(self.config.path, relative_path), self.config)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 54, in __init__
    self.process_single_file(p)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 67, in process_single_file
    self.process_single_file(p)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 67, in process_single_file
    self.data.append(self.process_single_item(item))
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 81, in process_single_item
    self.data.append(self.process_single_item(item))
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 81, in process_single_item
    text, targets = get_tokenized_input(item, "inputs"), get_tokenized_input(item, "targets")
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/utils.py", line 60, in get_tokenized_input
    text, targets = get_tokenized_input(item, "inputs"), get_tokenized_input(item, "targets")
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/utils.py", line 60, in get_tokenized_input
    assert pretokenized_key in item
AssertionError    
assert pretokenized_key in item
AssertionError
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 62, in main
    evaluate_all_tasks(args.data_path, model, tokenizer, args.task, task_classes)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 36, in evaluate_all_tasks
    task.evaluate()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 74, in evaluate
    dataset = self.build_dataset(file)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 167, in build_dataset
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 62, in main
    return GenerationTaskDataset(join(self.config.path, relative_path), self.config)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 54, in __init__
    evaluate_all_tasks(args.data_path, model, tokenizer, args.task, task_classes)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 36, in evaluate_all_tasks
    self.process_single_file(p)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 67, in process_single_file
    task.evaluate()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 74, in evaluate
    dataset = self.build_dataset(file)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 167, in build_dataset
    self.data.append(self.process_single_item(item))
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 81, in process_single_item
    return GenerationTaskDataset(join(self.config.path, relative_path), self.config)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 54, in __init__
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
    text, targets = get_tokenized_input(item, "inputs"), get_tokenized_input(item, "targets")
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/utils.py", line 60, in get_tokenized_input
    self.process_single_file(p)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 67, in process_single_file
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 62, in main
    assert pretokenized_key in item
AssertionError
    self.data.append(self.process_single_item(item))
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 81, in process_single_item
    evaluate_all_tasks(args.data_path, model, tokenizer, args.task, task_classes)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 36, in evaluate_all_tasks
    text, targets = get_tokenized_input(item, "inputs"), get_tokenized_input(item, "targets")
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/utils.py", line 60, in get_tokenized_input
    task.evaluate()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 74, in evaluate
    assert pretokenized_key in item
AssertionError
    dataset = self.build_dataset(file)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 167, in build_dataset
    return GenerationTaskDataset(join(self.config.path, relative_path), self.config)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 54, in __init__
    self.process_single_file(p)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 67, in process_single_file
    self.data.append(self.process_single_item(item))
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 81, in process_single_item
    text, targets = get_tokenized_input(item, "inputs"), get_tokenized_input(item, "targets")
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/utils.py", line 60, in get_tokenized_input
    assert pretokenized_key in item
AssertionError
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 62, in main
    evaluate_all_tasks(args.data_path, model, tokenizer, args.task, task_classes)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 36, in evaluate_all_tasks
    task.evaluate()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 74, in evaluate
    dataset = self.build_dataset(file)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 167, in build_dataset
    return GenerationTaskDataset(join(self.config.path, relative_path), self.config)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 54, in __init__
    self.process_single_file(p)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 67, in process_single_file
    self.data.append(self.process_single_item(item))
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 81, in process_single_item
    text, targets = get_tokenized_input(item, "inputs"), get_tokenized_input(item, "targets")
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/utils.py", line 60, in get_tokenized_input
    assert pretokenized_key in item
AssertionError
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 62, in main
    evaluate_all_tasks(args.data_path, model, tokenizer, args.task, task_classes)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 36, in evaluate_all_tasks
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 67, in <module>
    task.evaluate()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 74, in evaluate
    dataset = self.build_dataset(file)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 167, in build_dataset
    main()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 62, in main
    return GenerationTaskDataset(join(self.config.path, relative_path), self.config)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 54, in __init__
    evaluate_all_tasks(args.data_path, model, tokenizer, args.task, task_classes)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 36, in evaluate_all_tasks
    self.process_single_file(p)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 67, in process_single_file
    task.evaluate()
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 74, in evaluate
    self.data.append(self.process_single_item(item))
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 81, in process_single_item
    dataset = self.build_dataset(file)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/tasks.py", line 167, in build_dataset
    text, targets = get_tokenized_input(item, "inputs"), get_tokenized_input(item, "targets")
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/utils.py", line 60, in get_tokenized_input
    assert pretokenized_key in item
AssertionError
    return GenerationTaskDataset(join(self.config.path, relative_path), self.config)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 54, in __init__
    self.process_single_file(p)
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 67, in process_single_file
    self.data.append(self.process_single_item(item))
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/dataset.py", line 81, in process_single_item
    text, targets = get_tokenized_input(item, "inputs"), get_tokenized_input(item, "targets")
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/utils.py", line 60, in get_tokenized_input
    assert pretokenized_key in item
AssertionError
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 317471) of binary: /mnt/yrfs/qinkai/miniconda3/envs/largescale/bin/python
Traceback (most recent call last):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.0', 'console_scripts', 'torchrun')())
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/yrfs/xuyifan/GLM-130B/evaluate.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-09-22_22:37:44
  host      : node15
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 317472)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-09-22_22:37:44
  host      : node15
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 317473)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2022-09-22_22:37:44
  host      : node15
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 317474)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2022-09-22_22:37:44
  host      : node15
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 317476)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2022-09-22_22:37:44
  host      : node15
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 317477)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2022-09-22_22:37:44
  host      : node15
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 317480)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2022-09-22_22:37:44
  host      : node15
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 317481)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-09-22_22:37:44
  host      : node15
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 317471)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
